============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.2.0, pluggy-1.0.0
rootdir: /home/clapp_stanford_edu/Src/sep-python
collected 7 items

test_Hypercube.py .                                                      [ 14%]
test_modes.py .                                                          [ 28%]
test_sepfile.py .....                                                    [100%]

=============================== warnings summary ===============================
test/test_sepfile.py::test_simpleWriteHistoryGCS
test/test_sepfile.py::test_simpleWriteReadGCP
  /home/clapp_stanford_edu/.local/lib/python3.10/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function sGcsObj.__del__ at 0x7f1233488700>
  
  Traceback (most recent call last):
    File "/home/spack/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.5.0/python-3.10.8-tye3styllri3xiql6psptyz7uujbz4hn/lib/python3.10/site-packages/sepPython/sepIO.py", line 719, in __del__
      raise Exception("")
  Exception
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================== 7 passed, 2 warnings in 2.41s =========================
Must close gcs object before the delete is called
Exception ignored in: <function sGcsObj.__del__ at 0x7f1233488700>
Traceback (most recent call last):
  File "/home/spack/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.5.0/python-3.10.8-tye3styllri3xiql6psptyz7uujbz4hn/lib/python3.10/site-packages/sepPython/sepIO.py", line 719, in __del__
Exception: 
